name: Run Journey Tests on GitHub
description: Run AI Assistant journey tests

inputs:
  ai-defra-search-agent:
    description: commit hash of ai-defra-search-agent
  ai-defra-search-frontend:
    description: commit hash of ai-defra-search-frontend
  branch:
    description: branch in this repo
    default: main
  journey-test-pr:
    description: is this action being called from a pr in this repo?
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Docker Login
      uses: DEFRA/cdp-build-action/docker-login@main

    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Setup the tests
      run: npm i
      shell: bash
    - name: Start docker compose
      shell: bash
      run: |
          AI_DEFRA_SEARCH_BACKEND=${{inputs.ai-defra-search-agent}} \
          AI_DEFRA_SEARCH_FRONTEND=${{inputs.ai-defra-search-frontend}} \
          docker compose up --wait --wait-timeout 300 -d --quiet-pull
    - name: Run the tests
      shell: bash
      run: |
        npm run test:github
        npm run report
    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash
    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report
    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt
