name: Check Pull Request

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  security-scan:
    name: Security Scanning
    uses: ./.github/workflows/scan.yml
    secrets: inherit

  cdp-workflows:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
<<<<<<< Updated upstream
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
=======
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
>>>>>>> Stashed changes

      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint

  journey-tests:
    name: Run Journey Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
<<<<<<< Updated upstream
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
=======
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
>>>>>>> Stashed changes
      - name: Run Journey Tests
        uses: ./run-journey-tests
        with:
          journey-test-pr: true

  accessibility-tests:
    name: Run Accessibility Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
<<<<<<< Updated upstream
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
=======
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
>>>>>>> Stashed changes
      - name: Run Accessibility Tests
        uses: ./run-accessibility-tests
        with:
          journey-test-pr: true

